// أسماء الإعدادات بالعربي (خيار المالك «ب» — الحوكمة تصونها). يُوسَّع مع ظهور إعدادات جديدة.
// غير المعروف → يُنظَّف اسمه (احتياط)، حتى نضيف له اسمًا عربيًّا.
const SETTING_AR: Record<string, string> = {
  baseline_window: 'نافذة الأساس',
  exp_short: 'المتوسّط السريع',
  exp_long: 'المتوسّط البطيء',
  exp_mult: 'معامل التوسّع',
  wide_mult: 'معامل الاتّساع',
  narrow_mult: 'معامل الضيق',
  min_candles: 'أقلّ عدد شموع',
  min_data_points: 'أقلّ عدد نقاط',
  window: 'النافذة',
  period: 'الفترة',
  threshold: 'العتبة',
  interval_ms: 'الفاصل (مللي ثانية)',
  timeout_ms: 'المهلة (مللي ثانية)',
  lookback: 'النظر للخلف',
  smoothing: 'التنعيم',
  fast: 'السريع',
  slow: 'البطيء',
  fast_period: 'الفترة السريعة',
  slow_period: 'الفترة البطيئة',
  multiplier: 'المعامل',
  min_volume: 'أقلّ حجم',
  max_age_s: 'أقصى قِدَم (ثانية)',
  retention_days: 'أيام الاحتفاظ',
  archive_after_days: 'الأرشفة بعد (أيام)',
  batch_size: 'حجم الدفعة',
  // معاملات أقسام 200/250/300/350 الحقيقية (مسح المانيفستات 2026-08-19 — بند ٩ بورقة ٩٩)
  timeout_seconds: 'مهلة الدورة (ثوانٍ)',
  window_size: 'حجم النافذة',
  absorption_ratio: 'نسبة الامتصاص',
  reference_symbol: 'الرمز المرجعي',
  strong_threshold: 'عتبة القوّة',
  moderate_threshold: 'عتبة الاعتدال',
  slope_threshold: 'عتبة الميل',
  fit_threshold: 'عتبة المطابقة',
  z_threshold: 'عتبة درجة Z',
  skew_threshold: 'عتبة الالتواء',
  kurt_threshold: 'عتبة التفلطح',
  iqr_multiplier: 'معامل المدى الربيعي',
  bin_count: 'عدد الفئات',
  tail_ratio: 'نسبة الذيل',
  high_band: 'النطاق الأعلى',
  low_band: 'النطاق الأدنى',
  min_quality: 'أدنى جودة',
  drift_band: 'نطاق الانحراف',
  vol_band: 'نطاق التذبذب',
  base_prob: 'الاحتمال الأساس',
  confirmation_step: 'خطوة التأكيد',
  max_prob: 'الاحتمال الأقصى',
  exhaustion_factor: 'معامل الإنهاك',
  confluence_boost: 'تعزيز التقاطع',
  fvg_boost: 'تعزيز الفجوة',
  sweep_prob: 'احتمال الكنس',
  decay_per_candle: 'التلاشي لكل شمعة',
  horizon_candles: 'أفق الشموع',
  r_squared_weight: 'وزن معامل التحديد',
  mean_reverting_weight: 'وزن الارتداد للمتوسط',
  range_structure_weight: 'وزن بنية المدى',
  trending_prob: 'احتمال الاتجاه',
  neutral_band: 'نطاق الحياد',
  band: 'النطاق',
  min_confidence: 'الثقة الدنيا',
  min_samples: 'أدنى عدد عيّنات',
  validation_size: 'حجم عيّنة التحقق',
  min_accuracy: 'أدنى دقّة',
  min_improvement: 'أدنى تحسّن',
}

export function settingLabel(key: string): string {
  return SETTING_AR[key] ?? key.replace(/_/g, ' ')
}
