// أسماء التيارات/الأحداث بالعربي — قاموس مشترك واحد لكل الشاشات (بند 10/13 من دفتر 97):
// «التنبيهات» و«التشخيص» و«المراقبة» و«الرئيسية» كلها تقرأ من هون — لا قواميس متفرّقة.
// القاعدة (المثبتة بالورقة): المعروف يُترجم، والغريب يظهر باسمه الخام — صدق أوضح من إخفائه.

// ترجمة دقيقة للتيارات الحيّة الشائعة (المرصودة فعلًا على الناقل)
const EXACT: Record<string, string> = {
  'market.tick': 'أسعار السوق (تكّات)',
  'market.tick.validated': 'تكّات مدقَّقة',
  'market.trade': 'صفقات السوق',
  'market.volume': 'حجم السوق',
  'market.depth': 'عمق السوق',
  'market.news': 'أخبار السوق',
  'market.calendar': 'التقويم الاقتصادي',
  'market.reference': 'السعر المرجعي',
  'market.symbol_specs': 'مواصفات الرموز',
  'market.ctrader.symbol_specs': 'مواصفات رموز سي-تريدر',
  'market.structure.updated': 'البنية',
  'market.liquidity.updated': 'السيولة',
  'market.outcome.realized': 'نتائج الصفقات المحقَّقة',
  'market.time.drift': 'انحراف ساعة السوق',
  'market.feed.provider_down': 'سقوط مزوّد السوق',
  'market.feed.provider_recovered': 'رجوع مزوّد السوق',
  'market_data.candle_closed': 'الشموع (إغلاق شمعة)',
  'market_data.price_received': 'استقبال الأسعار',
  'market_data.volume_received': 'استقبال الحجم',
  'market_data.news_received': 'استقبال الأخبار',
  'market_data.calendar_event': 'حدث تقويم اقتصادي',
  'market_data.calendar_window': 'نافذة التقويم',
  'market_data.calendar.state': 'حالة التقويم',
  'market_data.cleaned': 'بيانات سوق منظَّفة',
  'market_data.normalized': 'بيانات سوق موحَّدة',
  'market_data.feed_interrupted': 'انقطاع التغذية',
  'market_data.feed_recovered': 'رجوع التغذية',
  'market_data.feed.state': 'حالة التغذية',
  'market_data.quality_alert': 'إنذار جودة البيانات',
  'market_data.quality.state': 'جودة بيانات السوق',
  'market_data.spread_updated': 'الفرق السعري',
  'market_data.depth_updated': 'تحديث العمق',
  'market_data.trade_tape_updated': 'شريط الصفقات',
  'market_data.reference_index_updated': 'المؤشّر المرجعي',
  'market_data.validation_failed': 'فشل تدقيق بيانات السوق',
  'market_data.validation.state': 'حالة تدقيق البيانات',
  'market_data.state': 'حالة بيانات السوق',
  'analysis.raw.completed': 'التحليل الحي',
  'analysis.fast.state': 'بطاقة المسار السريع (تكّات)',
  'analysis.slow.state': 'بطاقة المسار البطيء (شموع)',
  'analysis.cycle.collected': 'دورة التحليل',
  'analysis.setting.changed': 'تغيّر إعداد محلّل',
  'analysis.settings.command': 'أمر إعدادات التحليل',
  'structure.cycle.collected': 'دورة البنية',
  'structure.cycle.validated': 'تدقيق دورة البنية',
  'structure.validation_failed': 'فشل تدقيق البنية',
  'liquidity.cycle.collected': 'دورة السيولة',
  'liquidity.cycle.validated': 'تدقيق دورة السيولة',
  'liquidity.validation_failed': 'فشل تدقيق السيولة',
  'stats.cycle.collected': 'دورة الإحصاء',
  'probability.cycle.collected': 'دورة الاحتمالات',
  'strategy.cycle.collected': 'دورة الاستراتيجيات',
  'decision.cycle.collected': 'دورة القرار',
  'decision.aggregated.state': 'تجميع أدلّة القرار',
  'decision.scored.state': 'درجة القرار',
  'decision.resolved.state': 'حلّ تعارض القرار',
  'decision.filtered.state': 'فلتر القرار',
  'decision.approved.state': 'موافقة القرار',
  'decision.dispatch.state': 'إرسال القرار',
  'decision.evaluated.state': 'تقييم القرار',
  'decision.settings.state': 'عيارات القرار',
  'decision.settings.command': 'أمر عيارات القرار',
  'parameter.approve.command': 'أمر اعتماد مُعامِل معلن',
  'parameter.approved.state': 'اعتماد مُعامِل معلن',
  'dial.profile.state': 'ملفّ العيار (التعرّض)',
  'dial.command': 'أمر العيار',
  'tilt.rule.command': 'أمر قاعدة ترجيح',
  'tilt.rules.state': 'قواعد محرّك الترجيح',
  'tilt.state': 'حالة محرّك الترجيح',
  'risk.unified.state': 'حالة المخاطر الموحّدة',
  'risk.exposure.state': 'التعرّض',
  'risk.position_size.state': 'تحجيم المركز',
  'risk.position_size.rejected': 'رفض تحجيم المركز',
  'risk.structure_stop.state': 'الوقف الهيكلي',
  'risk.hard_stop.price': 'سعر الوقف الصلب',
  'risk.asset_ledger.state': 'دفتر مخاطر الأصل',
  'risk.asset_budget.state': 'ميزانيّة مخاطر الأصل',
  'risk.halt.requested': 'طلب إيقاف طارئ',
  'risk.kill_switch.reset_requested': 'طلب تصفير قاطع الأمان',
  'risk.loss_reported': 'تبليغ خسارة',
  'execution.gate.state': 'حالة بوّابة التنفيذ',
  'execution.gate.command': 'أمر بوّابة التنفيذ',
  'execution.unified.state': 'حالة التنفيذ الموحّدة',
  'execution.order.requested': 'طلب أمر',
  'execution.order.built': 'بناء أمر',
  'execution.order.legal': 'شرعيّة الأمر',
  'execution.order.skipped': 'أمر ما انبنى',
  'execution.order.rejected': 'أمر مرفوض',
  'execution.order.resolved': 'حلّ رمز الأمر',
  'execution.manage.intent': 'نيّة إدارة صفقة',
  'execution.manage.command': 'أمر إدارة صفقة',
  'execution.manage.written': 'انكتبت الإدارة للجسر',
  'execution.snapshot.state': 'لقطة التنفيذ',
  'execution.reconcile.state': 'مطابقة المراكز',
  'execution.reconcile.requested': 'طلب مطابقة المراكز',
  'execution.desired.state': 'الوضع المطلوب',
  'execution.quality.state': 'جودة التنفيذ',
  'execution.reference_divergence.state': 'انحراف السعر المرجعي',
  'execution.command.ack': 'تأكيد أمر تنفيذ',
  'execution.command.failed': 'فشل أمر تنفيذ',
  'execution.confirmation.rejected': 'رفض تأكيد التنفيذ',
  'trading.final_decision': 'قرار نهائي (انبعت للجسر)',
  'platform.account.state': 'حالة حساب التنفيذ',
  'platform.positions.state': 'مراكز المنصّة',
  'platform.terminal_state': 'حالة طرفيّة ميتاتريدر 5',
  'platform.trade_event': 'حدث صفقة من المنصّة',
  'platform.position.appeared': 'ظهور مركز بالمنصّة',
  'platform.position.vanished': 'اختفاء مركز من المنصّة',
  'platform.brain_signal.written': 'انكتبت إشارة الدماغ',
  'platform.brain_signal.write_failed': 'فشل كتابة إشارة الدماغ',
  'platform.brain_signal.halted': 'إشارة الدماغ موقوفة',
  'perpetual.pair.state': 'زوج المركز الدائم',
  'perpetual.target.state': 'هدف المركز الدائم',
  'horizon.profile.state': 'ظل شخصية الأفق',
  'perpetual.plan.state': 'خطّة المركز الدائم',
  'perpetual.entry.state': 'دخول المركز الدائم',
  'perpetual.asset.activate': 'تفعيل أصل دائم',
  'perpetual.asset.deactivate': 'إيقاف أصل دائم',
  'perpetual.owner.escalation': 'تصعيد للمالك',
  'asset.portfolio.state': 'محفظة الأصول',
  'asset.extraction.state': 'سحب أرباح الأصل',
  'feed.mt5.tick': 'تغذية ميتاتريدر 5',
  'feed.ctrader.tick': 'تغذية سي-تريدر',
  'system.commands.state': 'بوّابة الأوامر (901)',
  'emergency.halt': 'إيقاف طارئ',
  'kernel.clock.heartbeat': 'نبض النواة',
  'time.utc.synced': 'مزامنة الوقت العالمي',
  'SYS_SECOND': 'نبضة الثانية',
  'SYS_5MIN': 'نبضة 5 دقائق',
  'SYS_HOUR': 'نبضة الساعة',
  'SYS_DAY': 'نبضة اليوم',
  'core.integrity.alert': 'إنذار سلامة النواة',
  'audit.trail.state': 'سجلّ التدقيق',
  'reference.health.state': 'صحّة المرجع',
  'allowed.symbols.state': 'قائمة الرموز المسموحة',
  'symbol.resolve.requested': 'طلب حلّ رمز',
  'symbol.resolve.result': 'نتيجة حلّ رمز',
  'symbol.resolve.orphaned': 'رمز بلا حلّ',
  'model.persisted': 'حُفظ النموذج',
  'model.persist_requested': 'طلب حفظ النموذج',
  // المُنذِر (831) — تنبيه موحّد من أحداث الإخفاق التي كانت بلا مستمع
  'system.alert': 'تنبيه المُنذِر (إخفاق نشط)',
  'system.alert.state': 'حالة المُنذِر (التنبيهات النشطة)',
  'system.alert.recovered': 'استرداد المُنذِر (انقضاء الصمت)',
  'storage.persistence.save_failed': 'فشل حفظ النماذج',
  'tools.integrity.violation': 'اختراق سلامة الملفات',
  'tools.backup.failed': 'فشل النسخ الاحتياطي',
  'tools.file_archive.failed': 'فشل أرشفة الملفات',
  'tools.file_cleanup.failed': 'فشل تنظيف الملفات',
  'tools.storage.low': 'مساحة التخزين منخفضة',
  'time.utc.stale': 'تقادم مزامنة UTC',
  'time.ntp.drift': 'انحراف NTP (تجاوز العتبة)',
  'financial.truth.shortage': 'نقص الحقيقة المالية (هامش)',
  'storage.symbol.unmapped': 'رمز غير مسجّل',
  'time.clock.divergence': 'انحراف الساعة',
}

// عائلات — لأي اسم غير معروف بالضبط، نعرّف على الأقل عائلته بالعربي
const FAMILY: Array<[string, string]> = [
  ['market_data.', 'بيانات السوق'],
  ['market.', 'السوق'],
  ['analysis.', 'التحليل'],
  ['structure.', 'البنية'],
  ['liquidity.', 'السيولة'],
  ['stats.', 'الإحصاء'],
  ['probability.', 'الاحتمالات'],
  ['strategy.', 'الاستراتيجيات'],
  ['decision.', 'القرار'],
  ['risk.', 'المخاطر'],
  ['execution.', 'التنفيذ'],
  ['platform.', 'المنصّة'],
  ['portfolio.', 'المحفظة'],
  ['perpetual.', 'المركز الدائم'],
  ['asset.', 'الأصل'],
  ['storage.', 'التخزين'],
  ['learning.', 'التعلّم الآلي'],
  ['tools.', 'الأدوات'],
  ['feed.', 'التغذية'],
  ['symbol.', 'الرموز'],
  ['system.', 'النظام'],
  ['kernel.', 'النواة'],
  ['dial.', 'العيار'],
  ['tilt.', 'الترجيح'],
  ['audit.', 'التدقيق'],
  ['reference.', 'المرجع'],
  ['emergency.', 'الطوارئ'],
  ['trading.', 'التداول'],
  ['model.', 'النموذج'],
  ['atom.', 'الذرّات'],
]

/** اسم التيار بالعربي. الغريب تمامًا يرجع باسمه الخام (لا «غير معروف» أبدًا). */
export function streamAr(ev: string): string {
  const exact = EXACT[ev]
  if (exact) return exact
  for (const [prefix, family] of FAMILY) {
    if (ev.startsWith(prefix)) return `${family}: ${ev.slice(prefix.length)}`
  }
  return ev
}

/** هل عندنا ترجمة دقيقة (لا عائلة ولا خام)؟ — للشاشات اللي بدها تعرض الخام جنب المعروف */
export const streamKnown = (ev: string): boolean => ev in EXACT

// ——— أحداث المراقبة (الرئيسية/المراقبة): معنى محدَّد + لون — بدل «صفقة / أمر» العامّة ———
const EVENT_COLOR: Array<[RegExp, string]> = [
  [/provider_down|feed_interrupted|halt|\.rejected|failed|violation|alert/i, 'red'],
  [/provider_recovered|feed_recovered|written|built|final_decision|realized/i, 'green'],
  [/skipped|unhealthy|stopped|requested/i, 'amber'],
]

/** (نصّ عربي محدَّد · لون) لحدث مراقبة — من نفس القاموس المشترك */
export function eventAr(name: string): [string, string] {
  const label = streamAr(name)
  for (const [re, c] of EVENT_COLOR) if (re.test(name)) return [label, c]
  return [label, 'grey']
}
